service: league-process-ranking-scheduler

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  leagueProcessRankingScheduler:
    handler: handler.handler
    name: league-process-ranking-scheduler

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    #httpPort: 3000 # Esta configuração permanece útil para testes locais com serverless-offline
